name: Security Scan with Snyk

on:
  push:
    branches: [main]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Snyk and Run Security Scan
      run: |
        npm install -g snyk
        snyk test || true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
